configGetPutDelete:
  get:
    description: 'Get a specific configuration.'
    responses:
      '200':
        description: OK
        content:
          'application/json':
            schema:
              $ref: './components/config.yml'
      '401':
        description: Unauthorized.
      '404':
        description: Config does not exist for the authenticated user.
      '500':
        description: An error un-related to this request occurred.
    parameters:
      - $ref: './components/jwtcookie.yml'
      - $ref: './components/configId.yml'

  put:
    description: 'Update a specific configuration.'
    responses:
    '200':
      description: Configuration successfully updated.
    '400':
      description: configId does not match the actual config ID of the configuration provided.
    '401':
      description: Unauthorized.
    '404':
      description: Config does not exist for the authenticated user.
    '500':
      description: An error un-related to this request occurred.
    requestBody:
      content:
        'application/json':
          schema:
            $ref: './components/config.yml'
    parameters:
      - $ref: './components/jwtcookie.yml'
      - $ref: './components/configId.yml'

  delete:
    description: 'Delete a specific configuration.'
    responses:
      '200':
        description: Configuration successfully deleted.
      '401':
        description: Unauthorized.
      '500':
        description: An error un-related to this request occurred.
    parameters:
      - $ref: './components/jwtcookie.yml'
      - $ref: './components/configId.yml'

configPost:
  post:
    description: 'Save a configuration to the database.'
    responses:
      '200':
        $ref: './components/config200.yml'
      '401':
        description: Unauthorized.
      '500':
        description: An error un-related to this request occurred.
    requestBody:
      content:
        'application/json':
          schema:
            $ref: './components/config.yml'
    parameters:
      - $ref: './components/jwtcookie.yml'
