post:
  description: 'Import a config for the user.'
  responses:
    '200':
      content:
        'application/json':
          schema:
            $ref: './components/config.yml'
    '401':
      description: Unauthorized.
    '404':
      description: Config does not exist.
    '500':
      description: An error un-related to this request occurred.
  requestBody:
    $ref: './components/config200.yml'
  parameters:
    - $ref: './components/jwtcookie.yml'
