get:
  description: 'Get a list of configs that the current user has access to. Note: This endpoint currently gets all configs by JWT.'
  responses:
    '200':
      description: OK
      content:
        'application/json':
          schema:
            type: array
            items:
              $ref: './components/config.yml'
    '401':
      description: Unauthorized.
    '500':
      description: An error un-related to this request occurred.
  parameters:
    - $ref: './components/jwtcookie.yml'
